language: node_js
node_js:
  - "8"
script:
  - yarn
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public/
  target_branch: master
  on:
    branch: src