baseURL = "https://gnkz.github.io/"
languageCode = "en-us"
title = "Gnkz's Notes"
theme = "cocoa"
author = "Gonzalo Sánchez"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = -110
identifier             = "about"
url                    = "/about/"

[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = false                         # whether to display small country flags for available translations
author                 = "Gonzalo Sánchez"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Blog de un full stack developer"
#email                  = "you@example.space"
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/gnkz"
#instagram              = "//instagram.com/you"
#px500                  = "//500px.com/username"
#lang                   = "en"
#linkedin               = "//linkedin.com/in/you"
noshowreadtime         = false                         # if true, don't show "<x> minutes read" in posts
selfintro              = "Full Stack Developer"                            # appears in the site header when set to a non-empty string
#twitter                = "//twitter.com/you"
#mastodon               = "//example.com/@you"

avatar = "img/avatar.png"